# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem
import requests
from bs4 import BeautifulSoup


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(255, 255, 255);\n"
" padding: 10px 20px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(" QPushButton {\n"
"  background-color: rgb(255, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  cursor: pointer;\n"
"  transition: box-shadow 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"            background-color: rgb(0, 143, 255); /* изменяем цвет при нажатии */\n"
"        }")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 728, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setStyleSheet(" QPushButton {\n"
"  background-color: rgb(0, 163, 255);\n"
"  color: rgb(255, 255, 255);\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  cursor: pointer;\n"
"  transition: box-shadow 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"            background-color: rgb(0, 143, 255); /* изменяем цвет при нажатии */\n"
"        }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setStyleSheet("\n"
" QPushButton {\n"
"  background-color: rgb(19, 136, 8);\n"
"  color: rgb(255, 255, 255);\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  cursor: pointer;\n"
"  transition: box-shadow 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"            background-color: rgb(0, 143, 255); /* изменяем цвет при нажатии */\n"
"        }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setStyleSheet("color: rgb(127, 127, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.radioButton = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_5.addWidget(self.radioButton)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setStyleSheet("  padding: 10px 20px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.get_search_item()
        self.update_list()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Головна"))
        self.label_2.setText(_translate("MainWindow", "Пошук товару"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введіть назву товару"))
        self.pushButton.setText(_translate("MainWindow", "Знайти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Пошук"))
        self.pushButton_2.setText(_translate("MainWindow", "Зберегти"))
        self.pushButton_3.setText(_translate("MainWindow", "Оновити"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Товари"))
        self.label_3.setText(_translate("MainWindow", "Налаштуйте зберігання товарів\n"
"для подальшого використання,\n"
"або перегляду.\n"
"Програма не несе відповідальність за будь які порушення норм сайту\n"
"Будь ласка використовуйте лише для ознайом. цілей\n"
""))
        self.radioButton.setText(_translate("MainWindow", "Custom file save"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "$_FILENAME"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Налаштування"))

    def get_search_item(self):
        self.pushButton.clicked.connect(self.parser_items)

    def parser_items(self):
        """
        Data parser from main URL
        """
        current_item = self.lineEdit.text() + "/"
        url = f"https://www.olx.ua/uk/list/q-" + current_item

        response = requests.get(url).text
        soup = BeautifulSoup(response, "html.parser")
        item1 = soup.find_all("h6", class_="css-16v5mdi er34gjf0")
        for i in item1:
            print(i.text)
            self.listWidget.addItem(QListWidgetItem(i.text))

    def update_list(self):
        self.pushButton_3.clicked.connect(self.update_func)

    def update_func(self):
        self.listWidget.clear()
        self.parser_items()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
